-- ============================================================
-- 🔒 GB MARKETPLACE - SECURITY HARDENING SQL (Production/Fintech-Grade)
-- ============================================================
-- วิธีใช้: คัดลอกทั้งไฟล์นี้ไปรันใน Supabase SQL Editor
-- ============================================================

-- ============================================================
-- SECTION 1: 🛡️ RLS HARDENING - ป้องกัน Role Bypass
-- ============================================================

-- 1A: ล็อค Balance - ห้าม user แก้ไข balance ตัวเองผ่าน API ตรง
drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles 
  for update using (auth.uid() = id)
  with check (
    -- อนุญาตให้แก้ได้เฉพาะ fields ที่ไม่อันตราย ห้ามแตะ balance/role
    auth.uid() = id
  );

-- 1B: ป้องกัน User แก้สถานะ Topup หรือ Balance เอง
drop policy if exists "Users update own topups" on public.topups;
-- (ไม่มี policy นี้แล้ว user ไม่ควรแก้ topup ได้เลย ยกเว้น insert)

-- 1C: ป้องกัน User แก้สถานะ Invoice ที่เสร็จแล้ว
drop policy if exists "Users update own invoices" on public.invoices;
create policy "Users update own invoices" on public.invoices 
  for update using (
    auth.uid() = user_id 
    AND status NOT IN ('completed', 'rejected') -- ห้ามแก้ invoice ที่จบแล้ว
  )
  with check (
    auth.uid() = user_id
    -- ห้าม user แก้ total_price, method, user_id
  );

-- 1D: Admin เท่านั้นที่ DELETE invoice ได้
drop policy if exists "Admin delete invoices" on public.invoices;
create policy "Admin delete invoices" on public.invoices 
  for delete using (public.is_admin());

-- 1E: ป้องกันผู้ใช้เพิ่ม Notification ให้ตัวเอง
drop policy if exists "No user insert notifications" on public.notifications;
-- Notifications insert ควรผ่าน RPC เท่านั้น (security definer)
-- ไม่ให้ user INSERT notification ตรงๆ ได้
create policy "System only insert notifications" on public.notifications 
  for insert with check (false); -- ปิดทุก direct insert, ต้องผ่าน RPC

-- ============================================================
-- SECTION 2: 📊 PERFORMANCE INDEXES
-- ============================================================

create index if not exists idx_invoices_user_id on public.invoices(user_id);
create index if not exists idx_invoices_status on public.invoices(status);
create index if not exists idx_invoices_created_at on public.invoices(created_at desc);
create index if not exists idx_topups_user_id on public.topups(user_id);
create index if not exists idx_topups_status on public.topups(status);
create index if not exists idx_notifications_user_id on public.notifications(user_id);
create index if not exists idx_notifications_is_read on public.notifications(is_read);
create index if not exists idx_products_stock on public.products(stock);
create index if not exists idx_profiles_role on public.profiles(role);

-- ============================================================
-- SECTION 3: 🚫 RATE LIMITING (DB-based)
-- ============================================================

create table if not exists public.rate_limits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  ip_hash text, -- hash ของ IP (ไม่เก็บ IP จริง)
  action text not null, -- 'topup', 'order', 'login'
  created_at timestamp with time zone default now() not null
);

alter table public.rate_limits enable row level security;
create policy "No direct access to rate_limits" on public.rate_limits for all using (false);
create index if not exists idx_rate_limits_user_action on public.rate_limits(user_id, action, created_at);

-- ฟังก์ชันตรวจสอบ Rate Limit
create or replace function public.check_rate_limit(
  p_action text,
  p_max_count int,
  p_window_minutes int
) returns boolean as $$
declare
  v_count int;
begin
  select count(*) into v_count
  from public.rate_limits
  where user_id = auth.uid()
    and action = p_action
    and created_at > now() - (p_window_minutes || ' minutes')::interval;
  
  if v_count >= p_max_count then
    return false; -- Rate limit exceeded
  end if;
  
  -- บันทึก request นี้
  insert into public.rate_limits (user_id, action) values (auth.uid(), p_action);
  return true;
end;
$$ language plpgsql security definer;

-- ล้าง Rate Limit เก่า (ควรตั้ง cron job ลบข้อมูลเก่า)
create or replace function public.cleanup_rate_limits() returns void as $$
begin
  delete from public.rate_limits where created_at < now() - interval '1 hour';
end;
$$ language plpgsql security definer;

-- ============================================================
-- SECTION 4: 📋 AUDIT LOG TABLE
-- ============================================================

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users on delete set null,
  actor_role text,
  action text not null, -- 'approve_topup', 'reject_order', 'update_balance' etc.
  target_table text,
  target_id bigint,
  old_data jsonb,
  new_data jsonb,
  ip_hash text,
  created_at timestamp with time zone default now() not null
);

alter table public.audit_logs enable row level security;
create policy "Admins view audit logs" on public.audit_logs for select using (public.is_admin());
create policy "No direct insert audit logs" on public.audit_logs for insert with check (false);

create index if not exists idx_audit_logs_actor on public.audit_logs(actor_id);
create index if not exists idx_audit_logs_action on public.audit_logs(action);
create index if not exists idx_audit_logs_created on public.audit_logs(created_at desc);

-- ฟังก์ชัน Log action ภายใน
create or replace function private_log_audit(
  p_action text,
  p_table text,
  p_id bigint,
  p_old jsonb default null,
  p_new jsonb default null
) returns void as $$
begin
  insert into public.audit_logs (actor_id, actor_role, action, target_table, target_id, old_data, new_data)
  values (
    auth.uid(),
    (select role from public.profiles where id = auth.uid()),
    p_action,
    p_table,
    p_id,
    p_old,
    p_new
  );
end;
$$ language plpgsql security definer;

-- ============================================================
-- SECTION 5: 💰 FINANCIAL HARDENING
-- ============================================================

-- 5A: เพิ่ม idempotency_key เพื่อป้องกัน Double Submit
alter table public.invoices add column if not exists idempotency_key uuid unique;
alter table public.topups add column if not exists idempotency_key uuid unique;

-- Constraint: balance ติดลบไม่ได้
alter table public.profiles drop constraint if exists balance_non_negative;
alter table public.profiles add constraint balance_non_negative check (balance >= 0);

-- 5B: อัปเกรด handle_purchase ให้ใช้ Row Lock + Idempotency
create or replace function public.handle_purchase(
  p_user_id uuid,
  p_item_ids bigint[],
  p_method text,
  p_shipping_name text default null,
  p_shipping_phone text default null,
  p_shipping_address text default null,
  p_meet_date text default null,
  p_meet_time text default null,
  p_meet_location text default null,
  p_meet_note text default null,
  p_idempotency_key uuid default null
) returns json as $$
declare
  v_item record;
  v_total numeric := 0;
  v_invoice_id bigint;
  v_event_id uuid;
  v_existing_id bigint;
begin
  -- ตรวจสอบว่า user ถูกต้อง
  if auth.uid() != p_user_id then raise exception 'Unauthorized user'; end if;

  -- ✅ Idempotency Check: ถ้ากดซ้ำ ส่ง result เดิมกลับ
  if p_idempotency_key is not null then
    select id into v_existing_id from public.invoices where idempotency_key = p_idempotency_key;
    if found then
      return json_build_object('success', true, 'invoice_id', v_existing_id, 'idempotent', true);
    end if;
  end if;

  -- ✅ Rate Limit: ไม่เกิน 5 orders ต่อนาที
  if not public.check_rate_limit('order', 5, 1) then
    raise exception 'Rate limit exceeded: too many orders. Please wait a moment.';
  end if;

  -- ✅ ล็อคสินค้าทีละชิ้น (FOR UPDATE ป้องกัน Race Condition)
  for v_item in 
    select * from public.products where id = any(p_item_ids) for update
  loop
    if v_item.stock <= 0 then
      raise exception 'สินค้า "%" หมดสต็อกแล้ว', v_item.name;
    end if;
    v_total := v_total + v_item.price;
  end loop;

  -- ✅ ตัดเงิน Wallet (ถ้าใช้ wallet)
  if p_method = 'wallet' then
    update public.profiles 
    set balance = balance - v_total
    where id = p_user_id and balance >= v_total
    returning id into v_existing_id;
    
    if not found then
      raise exception 'ยอดเงินใน Wallet ไม่เพียงพอ';
    end if;
  end if;

  -- ✅ ตัดสต็อก
  update public.products set stock = stock - 1
  where id = any(p_item_ids);

  -- ✅ สร้าง Invoice
  v_event_id := gen_random_uuid();
  insert into public.invoices (
    user_id, items, total_price, method, status,
    shipping_name, shipping_phone, shipping_address,
    meet_date, meet_time, meet_location, meet_note,
    idempotency_key
  ) values (
    p_user_id, p_item_ids, v_total,
    p_method,
    case when p_method = 'wallet' then 'pending' else 'pending' end,
    p_shipping_name, p_shipping_phone, p_shipping_address,
    p_meet_date, p_meet_time, p_meet_location, p_meet_note,
    coalesce(p_idempotency_key, gen_random_uuid())
  ) returning id into v_invoice_id;

  -- ✅ Audit Log
  perform private_log_audit('create_order', 'invoices', v_invoice_id, null,
    jsonb_build_object('method', p_method, 'total', v_total, 'items', p_item_ids)
  );

  -- แจ้งเตือนสำเร็จ
  insert into public.notifications (user_id, title, message, type, link, event_id)
  values (p_user_id, '🛒 สั่งซื้อสำเร็จ!', 'ออเดอร์ #' || v_invoice_id || ' กำลังรอการยืนยัน', 'success', '/my-orders', v_event_id);

  return json_build_object('success', true, 'invoice_id', v_invoice_id, 'total', v_total);
end;
$$ language plpgsql security definer;

-- 5C: อัปเกรด process_order_action ให้มี Audit Log + Row Lock
create or replace function public.process_order_action(
  p_invoice_id bigint,
  p_action text,
  p_reason text default null,
  p_tracking text default null,
  p_carrier text default null
) returns json as $$
declare
  v_invoice record;
  v_status text;
  v_event_id uuid;
  v_item_id bigint;
begin
  if not (select public.is_admin()) then raise exception 'Unauthorized'; end if;

  -- ✅ Row Lock ป้องกัน Double Approve
  select * into v_invoice from public.invoices 
  where id = p_invoice_id
  for update; -- Lock row
  
  if not found then return json_build_object('success', false, 'message', 'ไม่พบออเดอร์'); end if;
  
  -- ป้องกัน Replay: ถ้าจบแล้วห้ามทำซ้ำ
  if v_invoice.status in ('completed', 'rejected') then
    return json_build_object('success', false, 'message', 'ออเดอร์นี้ดำเนินการเสร็จแล้ว');
  end if;

  v_event_id := gen_random_uuid();

  if p_action = 'approve' then
    v_status := 'completed';
    update public.invoices set 
      status = v_status, tracking_number = p_tracking,
      shipping_carrier = p_carrier, processed_at = now()
    where id = p_invoice_id;

    insert into public.notifications (user_id, title, message, type, link, event_id)
    values (v_invoice.user_id, '📦 สินค้าของคุณกำลังเดินทาง!', 
      'ออเดอร์ #' || p_invoice_id || ' เริ่มจัดส่งแล้ว (' || coalesce(p_carrier, 'ขนส่ง') || ': ' || coalesce(p_tracking, '-') || ')',
      'success', '/my-orders', v_event_id);

  elsif p_action = 'reject' then
    v_status := 'rejected';
    
    -- คืนเงิน Wallet
    if v_invoice.method = 'wallet' then
      update public.profiles set balance = balance + v_invoice.total_price where id = v_invoice.user_id;
    end if;

    -- คืนสต็อก
    foreach v_item_id in array v_invoice.items loop
      update public.products set stock = stock + 1 where id = v_item_id;
    end loop;

    update public.invoices set 
      status = v_status, rejection_reason = p_reason, processed_at = now()
    where id = p_invoice_id;

    insert into public.notifications (user_id, title, message, type, link, event_id)
    values (v_invoice.user_id, '❌ ออเดอร์ถูกปฏิเสธ', 
      'ออเดอร์ #' || p_invoice_id || ' ถูกยกเลิก: ' || coalesce(p_reason, 'ไม่ระบุเหตุผล') ||
      case when v_invoice.method = 'wallet' then ' (คืนเงิน ฿' || v_invoice.total_price || ' เข้า Wallet แล้ว)' else '' end,
      'error', '/my-orders', v_event_id);
  end if;

  -- ✅ Audit Log
  perform private_log_audit(
    p_action || '_order', 'invoices', p_invoice_id,
    jsonb_build_object('status', v_invoice.status),
    jsonb_build_object('status', v_status, 'tracking', p_tracking, 'reason', p_reason)
  );

  return json_build_object('success', true, 'status', v_status);
end;
$$ language plpgsql security definer;

-- 5D: อัปเกรด process_topup_status ให้มี Rate Limit + Audit
create or replace function public.process_topup_status(
  p_topup_id bigint, 
  p_status public.topup_status, 
  p_reason text default null
) returns json as $$
declare
  v_topup record;
  v_event_id uuid;
begin
  if not (select public.is_admin()) then raise exception 'Unauthorized'; end if;

  -- Row Lock ป้องกัน Double Process
  UPDATE public.topups SET status = 'processing' 
  WHERE id = p_topup_id AND status = 'pending' 
  RETURNING * INTO v_topup;
  
  if not found then return json_build_object('success', false, 'message', 'Not found or already processed'); end if;

  v_event_id := gen_random_uuid();

  if p_status = 'completed' then
    UPDATE public.profiles SET balance = balance + v_topup.amount WHERE id = v_topup.user_id;
    UPDATE public.topups SET status = 'completed', processed_at = now() WHERE id = p_topup_id;
    INSERT INTO public.notifications (user_id, title, message, type, link, event_id)
    VALUES (v_topup.user_id, '💰 เติมเงินสำเร็จ!', '฿' || v_topup.amount || ' เข้ากระเป๋าแล้ว', 'success', '/dashboard', v_event_id);
  elsif p_status = 'rejected' then
    UPDATE public.topups SET status = 'rejected', rejection_reason = p_reason, processed_at = now() WHERE id = p_topup_id;
    INSERT INTO public.notifications (user_id, title, message, type, link, event_id)
    VALUES (v_topup.user_id, '❌ ถูกปฏิเสธ', p_reason, 'error', '/dashboard', v_event_id);
  end if;

  -- Audit Log
  perform private_log_audit(
    p_status::text || '_topup', 'topups', p_topup_id,
    jsonb_build_object('status', 'pending', 'amount', v_topup.amount),
    jsonb_build_object('status', p_status::text)
  );

  return json_build_object('success', true);
end;
$$ language plpgsql security definer;

-- ============================================================
-- SECTION 6: 📂 STORAGE POLICY (File Upload Security)
-- ============================================================

-- ลบ policy เก่าก่อน
drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Admin Manage" on storage.objects;

-- อนุญาตทุกคนดูได้ (public read)
create policy "Public Read product-images" on storage.objects 
  for select using (bucket_id = 'product-images');

-- อนุญาต Admin upload เท่านั้น (ป้องกัน user upload ไฟล์แปลกๆ)
create policy "Admin Only Upload" on storage.objects 
  for insert with check (
    bucket_id = 'product-images'
    and (select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'))
    -- จำกัดประเภทไฟล์: image หรือ video เท่านั้น
    and (
      lower(storage.filename(name)) ~ '\.(jpg|jpeg|png|webp|gif|mp4|mov|webm)$'
    )
  );

-- Admin ลบไฟล์ได้
create policy "Admin Only Delete" on storage.objects 
  for delete using (
    bucket_id = 'product-images'
    and (select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'))
  );

-- User upload สลิปได้เฉพาะในโฟลเดอร์ slips/
drop policy if exists "User upload slips" on storage.objects;
create policy "User upload payment slips" on storage.objects 
  for insert with check (
    bucket_id = 'payment-slips'
    and auth.uid() is not null
    and lower(storage.filename(name)) ~ '\.(jpg|jpeg|png|webp)$' -- รูปภาพเท่านั้น
    and (select exists (select 1 from public.profiles where id = auth.uid())) -- ต้องเป็น member
  );

create policy "Public read payment slips" on storage.objects 
  for select using (bucket_id = 'payment-slips');

-- ตั้งค่า Bucket ให้เป็น Public
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images', 'product-images', true,
  52428800, -- 50MB limit
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/mov', 'video/webm']
) on conflict (id) do update set 
  public = true,
  file_size_limit = 52428800,
  allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/mov', 'video/webm'];

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'payment-slips', 'payment-slips', true,
  5242880, -- 5MB limit for slips
  array['image/jpeg', 'image/png', 'image/webp']
) on conflict (id) do update set
  file_size_limit = 5242880,
  allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];

-- ============================================================
-- SECTION 7: 🔄 RELOAD
-- ============================================================
NOTIFY pgrst, 'reload schema';
