-- ========================================================
-- 🏪 GB Marketplace - Supabase Master Setup (Hardened)
-- ========================================================

-- 1. ปรับปรุงตาราง Profiles (ใช้วิธี Migration ไม่ใช้ DROP)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique not null,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin')),
  real_email text, -- เก็บอีเมลจริงไว้แบบ Private
  balance numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ปรับปรุงตาราง Products (ถ้าไม่มี)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image_url text,
  description text,
  category text default 'มือ1',
  stock int default 1,
  condition_percent int default 100,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  images text default '[]',
  videos text default '[]'
);

-- 2. ระบบความปลอดภัย RLS (Security-First)
alter table public.profiles enable row level security;
alter table public.products enable row level security;

-- ✅ SECURITY DEFINER Function เพื่อแก้ปัญหา Recursion
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- Profiles: Public เห็นได้แค่ข้อมูลพื้นฐาน
drop policy if exists "Public profiles access" on public.profiles;
create policy "Public profiles access" on public.profiles for select using (true);

-- Profiles: เจ้าของจัดการตัวเองได้
drop policy if exists "Users view own profile" on public.profiles;
drop policy if exists "Users update own profile" on public.profiles;
create policy "Users view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users update own profile" on public.profiles for update using (auth.uid() = id);

-- Profiles: Admin ดูได้ทั้งหมด (ใช้ is_admin() เพื่อแก้ Recursion)
drop policy if exists "Admins view all profiles" on public.profiles;
create policy "Admins view all profiles" on public.profiles for select using (public.is_admin());

-- Products: ทุกคนดูได้
drop policy if exists "Public view products" on public.products;
create policy "Public view products" on public.products for select using (true);

-- Products: Admin เท่านั้นที่จัดการได้
drop policy if exists "Admin manage products" on public.products;
create policy "Admin manage products" on public.products 
  for all using (public.is_admin());

-- 3. ฟังก์ชัน RPC ปลอดภัย
create or replace function public.get_user_id_from_username(p_username text)
returns uuid as $$
begin
    return (select id from public.profiles where username = p_username);
end;
$$ language plpgsql security definer;

-- 4. ระบบ Trigger สร้าง Profile อัตโนมัติ
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url, real_email, role, balance)
  values (
    new.id, 
    new.raw_user_meta_data->>'username', 
    new.raw_user_meta_data->>'avatar_url', 
    new.raw_user_meta_data->>'real_email',
    'user',
    0
  );
  return new;
end;
$$ language plpgsql security definer;

do $$ begin
  if not exists (select 1 from pg_trigger where tgname = 'on_auth_user_created') then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end $$;

-- 5. ตารางเพิ่มเติม (Status Enums)
do $$ begin
  create type public.topup_status as enum ('pending', 'processing', 'completed', 'rejected');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.notification_type as enum ('info', 'success', 'warning', 'error', 'topup_request', 'topup_result');
exception
  when duplicate_object then null;
end $$;

-- Table: Invoices
create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  items bigint[] not null,
  total_price numeric default 0,
  method text not null,
  status text default 'pending',
  shipping_name text,
  shipping_phone text,
  shipping_address text,
  meet_date text,
  meet_time text,
  meet_location text,
  meet_note text,
  slip_url text,
  tracking_number text,
  shipping_carrier text,
  rejection_reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Topups
create table if not exists public.topups (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  amount numeric not null check (amount > 0),
  slip_url text,
  status public.topup_status default 'pending' not null,
  rejection_reason text,
  idempotency_key uuid unique default gen_random_uuid(),
  processed_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  CONSTRAINT valid_status_transition CHECK (status in ('pending', 'processing', 'completed', 'rejected'))
);

-- Table: Wishlist
create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  product_id bigint references public.products on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- Table: Notifications
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  title text not null,
  message text,
  type public.notification_type default 'info',
  link text,
  is_read boolean default false,
  event_id uuid unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: Settings
create table if not exists public.settings (
  id int primary key default 1,
  phone text,
  facebook text,
  wallet_number text,
  promptpay_number text,
  promptpay_qr text
);

-- RLS Enforcement
alter table public.invoices enable row level security;
alter table public.topups enable row level security;
alter table public.wishlist enable row level security;
alter table public.notifications enable row level security;
alter table public.settings enable row level security;

-- Policies for Invoices/Topups
create policy "Users view own invoices" on public.invoices for select using (auth.uid() = user_id);
create policy "Admins view all invoices" on public.invoices for select using (public.is_admin());
create policy "Users insert own invoices" on public.invoices for insert with check (auth.uid() = user_id);
create policy "Users update own invoices" on public.invoices for update using (auth.uid() = user_id);
create policy "Admins update all invoices" on public.invoices for update using (public.is_admin());

create policy "Users view own topups" on public.topups for select using (auth.uid() = user_id);
create policy "Admins view all topups" on public.topups for select using (public.is_admin());
create policy "Users insert own topups" on public.topups for insert with check (auth.uid() = user_id AND status = 'pending');

-- Policies for others
create policy "Users manage own wishlist" on public.wishlist for all using (auth.uid() = user_id);
create policy "Users view own notifications" on public.notifications for select using (auth.uid() = user_id);
create policy "Public view settings" on public.settings for select using (true);
create policy "Admin manage settings" on public.settings for all using (public.is_admin());

-- ========================================================
-- 🛡️ SPECIAL FUNCTIONS & LOGIC
-- ========================================================

-- Process Topup Logic
create or replace function public.process_topup_status(p_topup_id bigint, p_status public.topup_status, p_reason text default null)
returns json as $$
declare
    v_admin_id uuid;
    v_topup record;
    v_event_id uuid;
begin
    v_admin_id := auth.uid();
    if not (select public.is_admin()) then raise exception 'Unauthorized'; end if;

    UPDATE public.topups SET status = 'processing' WHERE id = p_topup_id AND status = 'pending' RETURNING * INTO v_topup;
    if not found then return json_build_object('success', false, 'message', 'Not found'); end if;

    v_event_id := gen_random_uuid();

    if p_status = 'completed' then
        UPDATE public.profiles SET balance = balance + v_topup.amount WHERE id = v_topup.user_id;
        UPDATE public.topups SET status = 'completed', processed_at = now() WHERE id = p_topup_id;
        INSERT INTO public.notifications (user_id, title, message, type, link, event_id)
        VALUES (v_topup.user_id, '💰 เติมเงินสำเร็จ!', '฿' || v_topup.amount || ' เข้ากระเป๋าแล้ว', 'success', '/dashboard', v_event_id);
    elsif p_status = 'rejected' then
        UPDATE public.topups SET status = 'rejected', rejection_reason = p_reason, processed_at = now() WHERE id = p_topup_id;
        INSERT INTO public.notifications (user_id, title, message, type, link, event_id)
        VALUES (v_topup.user_id, '❌ ถูกปฏิเสธ', p_reason, 'error', '/dashboard', v_event_id);
    end if;
    return json_build_object('success', true);
end;
$$ language plpgsql security definer;

-- Smart Login Resolver
create or replace function public.resolve_auth_email(p_identifier text)
returns text as $$
declare
    v_email text;
begin
    select u.email into v_email from auth.users u join public.profiles p on p.id = u.id left join public.topups t on t.user_id = p.id
    where lower(p.username) = lower(trim(p_identifier)) order by (t.id is not null) desc, p.created_at asc limit 1;
    if v_email is not null then return v_email; end if;

    select u.email into v_email from auth.users u join public.profiles p on p.id = u.id left join public.topups t on t.user_id = p.id
    where lower(p.real_email) = lower(trim(p_identifier)) order by (t.id is not null) desc, p.created_at asc limit 1;
    return COALESCE(v_email, p_identifier);
end;
$$ language plpgsql security definer;

-- ========================================================
-- SYNC & MAINTENANCE
-- ========================================================

-- Admin Promotion
DO $$
BEGIN
    UPDATE public.profiles SET role = 'admin' WHERE LOWER(real_email) = LOWER('admingbmoney@gbshop.com');
END $$;

-- Missing Columns & Keys Repair
ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_user_id_fkey;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE public.topups DROP CONSTRAINT IF EXISTS topups_user_id_fkey;
ALTER TABLE public.topups ADD CONSTRAINT topups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

-- Merge Duplicates
DO $$
DECLARE
    r RECORD;
    v_master_id uuid;
    v_dup_id uuid;
BEGIN
    FOR r IN (SELECT real_email FROM public.profiles WHERE real_email IS NOT NULL GROUP BY real_email HAVING count(*) > 1) LOOP
        SELECT p.id INTO v_master_id FROM public.profiles p LEFT JOIN public.topups t ON t.user_id = p.id WHERE p.real_email = r.real_email ORDER BY (t.id IS NOT NULL) DESC, p.created_at ASC LIMIT 1;
        FOR v_dup_id IN (SELECT id FROM public.profiles WHERE real_email = r.real_email AND id != v_master_id) LOOP
            UPDATE public.topups SET user_id = v_master_id WHERE user_id = v_dup_id;
            UPDATE public.invoices SET user_id = v_master_id WHERE user_id = v_dup_id;
            DELETE FROM public.profiles WHERE id = v_dup_id;
        END LOOP;
    END LOOP;
END $$;

-- Realtime Publication
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR ALL TABLES;

-- 7. ระบบการสั่งซื้ออัจฉริยะ (Atomic Purchase RPC)
-- ฟังก์ชันนี้จะจัดการตัดสต็อกและตัดเงินใน Wallet ในขั้นตอนเดียวเพื่อความปลอดภัย
create or replace function handle_purchase(
  p_user_id uuid,
  p_item_ids bigint[],
  p_method text,
  p_shipping_name text default null,
  p_shipping_phone text default null,
  p_shipping_address text default null,
  p_meet_date text default null,
  p_meet_time text default null,
  p_meet_location text default null,
  p_meet_note text default null
) returns json as $$
declare
  v_total_price numeric := 0;
  v_user_balance numeric := 0;
  v_product_id bigint;
  v_invoice_id bigint;
  v_item record;
  v_status text := 'pending';
begin
  -- 1. ตรวจสอบสต็อกสินค้าทุกชิ้นก่อน
  foreach v_product_id in array p_item_ids loop
    if not exists (select 1 from public.products where id = v_product_id and stock > 0) then
      raise exception 'สินค้าบางรายการหมดสต็อกแล้ว กรุณาตรวจสอบอีกครั้ง';
    end if;
  end loop;

  -- 2. คำนวณราคารวมทั้งหมด
  select sum(price) into v_total_price 
  from public.products 
  where id = any(p_item_ids);

  -- 3. หากชำระผ่าน Wallet ให้เช็คยอดเงินและหักเงินทันที
  if p_method = 'wallet' then
    select balance into v_user_balance from public.profiles where id = p_user_id;
    if v_user_balance < v_total_price then
      raise exception 'ยอดเงินใน Wallet ไม่เพียงพอ (ขาดอยู่ ฿%)', (v_total_price - v_user_balance);
    end if;

    -- ตัดเงิน
    update public.profiles 
    set balance = balance - v_total_price 
    where id = p_user_id;
    
    v_status := 'paid'; -- เปลี่ยนสถานะเป็นชำระแล้วกรณีจ่ายผ่าน Wallet
  end if;

  -- 4. หักสต็อกสินค้าทุกชิ้น
  foreach v_product_id in array p_item_ids loop
    update public.products 
    set stock = stock - 1 
    where id = v_product_id;
  end loop;

  -- 5. บันทึกรายการสั่งซื้อ (Invoice)
  insert into public.invoices (
    user_id, items, total_price, method, status, 
    shipping_name, shipping_phone, shipping_address,
    meet_date, meet_time, meet_location, meet_note
  ) values (
    p_user_id, p_item_ids, v_total_price, p_method, v_status,
    p_shipping_name, p_shipping_phone, p_shipping_address,
    p_meet_date, p_meet_time, p_meet_location, p_meet_note
  ) returning id into v_invoice_id;

  -- 6. สร้างแจ้งเตือนให้ผู้ใช้
  insert into public.notifications (user_id, title, message, type, link, event_id)
  values (
    p_user_id, 
    '📦 สั่งซื้อสำเร็จ!', 
    'ออเดอร์ #' || v_invoice_id || ' ของคุณได้รับการยืนยันแล้ว',
    'success',
    '/dashboard',
    gen_random_uuid()
  );

  return json_build_object(
    'success', true, 
    'invoice_id', v_invoice_id, 
    'total_price', v_total_price,
    'status', v_status
  );

exception when others then
  return json_build_object('success', false, 'message', sqlerrm);
end;
$$ language plpgsql security definer;

-- 8. ระบบจัดการคำสั่งซื้ออัจฉริยะ 2.0 (Order Action RPC)
-- ฟังก์ชันนี้จัดการการอนุมัติ (พร้อมเลขพัสดุ) และการปฏิเสธ (พร้อมคืนเงิน)
create or replace function process_order_action(
  p_invoice_id bigint,
  p_action text, -- 'approve' หรือ 'reject'
  p_reason text default null,
  p_tracking text default null,
  p_carrier text default null
) returns json as $$
declare
  v_invoice record;
  v_status text;
  v_event_id uuid;
begin
  -- 1. ตรวจสอบแอดมิน
  if not (select public.is_admin()) then raise exception 'Unauthorized'; end if;

  -- 2. ดึงข้อมูลออเดอร์
  select * into v_invoice from public.invoices where id = p_invoice_id;
  if not found then return json_build_object('success', false, 'message', 'ไม่พบออเดอร์'); end if;

  v_event_id := gen_random_uuid();

  -- 3. กรณีอนุมัติ (Approve)
  if p_action = 'approve' then
    v_status := 'completed';
    update public.invoices set 
      status = v_status,
      tracking_number = p_tracking,
      shipping_carrier = p_carrier,
      processed_at = now()
    where id = p_invoice_id;

    insert into public.notifications (user_id, title, message, type, link, event_id)
    values (
      v_invoice.user_id, 
      '📦 สินค้าของคุณกำลังเดินทาง!', 
      'ออเดอร์ #' || p_invoice_id || ' เริ่มจัดส่งแล้ว (' || coalesce(p_carrier, 'ขนส่ง') || ': ' || coalesce(p_tracking, '-') || ')',
      'success', '/dashboard', v_event_id
    );

  -- 4. กรณีปฏิเสธ (Reject)
  elsif p_action = 'reject' then
    v_status := 'rejected';
    
    -- คืนเงินเข้า Wallet หากชำระผ่าน Wallet
    if v_invoice.method = 'wallet' then
      update public.profiles 
      set balance = balance + v_invoice.total_price 
      where id = v_invoice.user_id;
    end if;

    -- คืนสต็อกสินค้า
    declare
      v_item_id bigint;
    begin
      foreach v_item_id in array v_invoice.items loop
        update public.products set stock = stock + 1 where id = v_item_id;
      end loop;
    end;

    update public.invoices set 
      status = v_status,
      rejection_reason = p_reason,
      processed_at = now()
    where id = p_invoice_id;

    insert into public.notifications (user_id, title, message, type, link, event_id)
    values (
      v_invoice.user_id, 
      '❌ ออเดอร์ถูกปฏิเสธ', 
      'ออเดอร์ #' || p_invoice_id || ' ถูกยกเลิก: ' || coalesce(p_reason, 'ไม่ระบุเหตุผล') || ' (คืนเงินเข้า Wallet แล้ว)',
      'error', '/dashboard', v_event_id
    );
  end if;

  return json_build_object('success', true, 'status', v_status);
end;
$$ language plpgsql security definer;

-- รีโหลด Schema
NOTIFY pgrst, 'reload schema';
